export enum ICON_NAMES {
  arrowDropDown = 'arrow-drop-down',
  arrowDropUp = 'arrow-drop-up',
  arrowRightUp = 'arrow-right-up',
  burger = 'burger',
  calendar = 'calendar',
  checkCircle = 'check-circle',
  check = 'check',
  clipboardCheck = 'clipboard-check',
  clock = 'clock',
  code = 'code',
  cube = 'cube',
  download = 'download',
  duplicate = 'duplicate',
  exclamationCircle = 'exclamation-circle',
  hashtag = 'hashtag',
  locationMarker = 'location-marker',
  plus = 'plus',
  refresh = 'refresh',
  shieldExclamation = 'shield-exclamation',
  xCircle = 'x-circle',
  x = 'x',
}
