export enum ICON_NAMES {
  arrowDropDown = 'arrow-drop-down',
  arrowDropUp = 'arrow-drop-up',
  arrowRightUp = 'arrow-right-up',
  burger = 'burger',
  calendar = 'calendar',
  checkCircle = 'check-circle',
  checkDouble = 'check-double',
  clipboardCheck = 'clipboard-check',
  clock = 'clock',
  code = 'code',
  cube = 'cube',
  download = 'download',
  duplicate = 'duplicate',
  exclamationCircle = 'exclamation-circle',
  exclamationTriangle = 'exclamation-triangle',
  hashtag = 'hashtag',
  keyboard = 'keyboard',
  locationMarker = 'location-marker',
  plus = 'plus',
  refresh = 'refresh',
  xCircle = 'x-circle',
  x = 'x',
  squareRoot = 'square-root',
  spinner = 'spinner',
}
