export enum ROUTE_NAMES {
  app = 'index',
  audits = 'audits',
  abi = 'abi',
  abiEncoderId = 'abi-encoder-id',
  abiDecoderId = 'abi-decoder-id',
  unixEpoch = 'unix-epoch',
  unixEpochDate = 'unix-epoch-date',
  unixEpochTimestamp = 'unix-epoch-timestamp',
  converter = 'converter',
  converterUnit = 'converter-unit',
  converterNumber = 'converter-number',
  hashFunction = 'hash-function',
  hashFunctionKeccak256Id = 'hash-function-keccak256-id',
  hashFunctionSha256Id = 'hash-function-sha256-id',
  hashFunctionRipemd160Id = 'hash-function-ripemd160-id',
  addressUtils = 'address-utils',
  addressUtilsCommonAddresses = 'address-utils-common-addresses',
  addressUtilsCreate = 'address-utils-create',
  addressUtilsCreate2 = 'address-utils-create2',
}
