export const ROUTE_PATH = {
  app: '/',
  audits: '/audits',
  abi: '/abi',
  abiEncoder: '/abi/encoder',
  abiDecoder: '/abi/decoder',
  unixEpoch: '/unix-epoch',
  unixEpochDate: '/unix-epoch/date',
  unixEpochTimestamp: '/unix-epoch/timestamp',
  converter: '/converter',
  converterUnit: '/converter/unit',
  converterNumber: '/converter/number',
  hashFunction: '/hash-function',
  hashFunctionKeccak256: '/hash-function/keccak256',
  hashFunctionSha256: '/hash-function/sha256',
  hashFunctionRipemd160: '/hash-function/ripemd160',
  addressUtils: '/address-utils',
  addressUtilsCommonAddresses: '/address-utils/common-addresses',
  addressUtilsCreate: '/address-utils/create',
  addressUtilsCreate2: '/address-utils/create2',
}
